packages:
  - apps/*
  - packages/*
allowBuilds:
  '@prisma/engines': true
  '@scarf/scarf': false
  esbuild: true
  prisma: true
minimumReleaseAgeExclude:
  - '@vitejs/plugin-react@6.1.2'
onlyBuiltDependencies:
  - "@prisma/engines"
  - prisma
  - esbuild
  - sharp
  - "@swc/core"
